### ISSUE TITLE
url of the repository?

### ISSUE THREAD

**Issue by java2men** [PicoScott/SwipeLayout#1]
Hi! 
Excellent implementation of swipelayout.
Are there plans to publish to the repository?
Thanks.

**Comment by PicoScott** [comment]
Sorry for  replying you so late, i will publish to the repository recently.

**Comment by java2men** [comment]
Здравствуйте!

**Comment by java2men** [comment]
Hello!
Is your project used in production? 
Or is it an educational or research project?
Thanks.

**Comment by PicoScott** [comment]
This idea originated in the project , it will be integrated into the project that I am developing. You can tell me that If you have any ideas or suggestions , I will join in the next version.
